### ISSUE TITLE
Could not get container for None

### ISSUE THREAD

**Issue by xoltar** [scitran/scitran#27]
After patching the code to make https://github.com/scitran/scitran/issues/26 work, I next encountered the following:

New Instance Detected

[...]

Would you like to bootstrap the database? [Y/n]:
Traceback (most recent call last):
  File "./scitran.py", line 1040, in <module>
    args.func(args)
  File "./scitran.py", line 773, in start
    bootstrap_db()
  File "./scitran.py", line 484, in bootstrap_db
    os.path.join(HERE, 'code'):        {'bind': '/service/code',   'ro': False },
  File "/home/bkeller/src/scitran/venv/lib/python2.7/site-packages/docker/client.py", line 904, in start
    self._raise_for_status(res)
  File "/home/bkeller/src/scitran/venv/lib/python2.7/site-packages/docker/client.py", line 119, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Could not get container for None")

**Comment by kofalt** [comment]
Closing as obsoleted; ref comments on #26.
